### ISSUE TITLE
newmetatable error after using the latest update

### ISSUE THREAD

**Issue by oserban** [torch/nn#1230]
The last commits broke something in the library as this was working fine a few days ago:

luajit: /torch/install/share/lua/5.1/torch/init.lua:102: class nn.ZipTable has been already assigned a parent class

stack traceback:
	[C]: in function 'newmetatable'
	/torch/install/share/lua/5.1/torch/init.lua:102: in function 'class'
	/torch/install/share/lua/5.1/rnnlib/nn/ZipTable.lua:12: in main chunk
	[C]: in function 'require'
	/torch/install/share/lua/5.1/rnnlib/init.lua:34: in main chunk
	[C]: in function 'require'

**Comment by nicholas-leonard** [comment]
@oserban `luarocks install dpnn && luarocks install nn` should fix it.

**Comment by oserban** [comment]
Unfortunately it does not solve the issue. I think this is still linked to the last commit ...
Do you have any other suggestion ?

**Comment by soumith** [comment]
@oserban we pushed a fix to dpnn. 
But @nicholas-leonard rnnlib also has a ZipTable: https://github.com/facebookresearch/torch-rnnlib/blob/master/rnnlib/nn/ZipTable.lua

**Comment by oserban** [comment]
@soumith thank you for the clarification
@nicholas-leonard can you please have a look at this issue, because I think many people are affected by this. I was unlucky enough to update the library today when the problem occurred ...

**Comment by nicholas-leonard** [comment]
@oserban To solve this, a PR needs to be sent to rnnlib to remove nn/ZipTable.lua.

**Comment by oserban** [comment]
https://github.com/facebookresearch/torch-rnnlib/pull/6
